version: '3.9'

services:
  chatbot:
    image: chatbot:latest
    container_name: chatbot
    volumes:
      - chatbot:/data
    environment:
      - DB_DIR=/data
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    command:  ["python", "app/manage.py", "runserver", "0.0.0.0:8000"]


volumes:
  chatbot:
    name: chatbot