# Generated by Django 4.2.7 on 2023-11-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="last_message_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
