# Generated by Django 4.2.7 on 2023-11-16 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0002_conversation_last_message_date_conversation_title"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="conversation",
            unique_together=set(),
        ),
    ]
