# Generated by Django 4.2.7 on 2023-11-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0005_alter_conversation_last_message_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="last_message_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
