# Generated by Django 4.2.7 on 2023-11-16 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0006_alter_conversation_last_message_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ["last_message_date"]},
        ),
    ]
