# Generated by Django 4.2.7 on 2023-11-16 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0007_alter_conversation_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ["-last_message_date"]},
        ),
    ]
