# Generated by Django 4.2.7 on 2023-11-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0008_alter_conversation_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-date"]},
        ),
        migrations.AddField(
            model_name="message",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
