# Generated by Django 4.2.7 on 2023-11-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0009_alter_message_options_message_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["date"]},
        ),
        migrations.AddField(
            model_name="conversation",
            name="dislike_count",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="conversation",
            name="like_count",
            field=models.BigIntegerField(default=0),
        ),
    ]
