# Generated by Django 4.2.7 on 2023-11-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "conversations",
            "0010_alter_message_options_conversation_dislike_count_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="last_message_date",
            field=models.DateTimeField(),
        ),
    ]
