# Generated by Django 4.2.7 on 2023-11-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0011_alter_conversation_last_message_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="dislike_count",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="like_count",
        ),
        migrations.AlterField(
            model_name="conversation",
            name="last_message_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
