# Generated by Django 4.2.7 on 2023-11-15 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbots", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatbot",
            old_name="creator",
            new_name="user",
        ),
    ]
