# Generated by Django 4.2.7 on 2023-11-21 06:44

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ("chatbots", "0002_vector_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="embedding",
            field=pgvector.django.VectorField(blank=True, dimensions=3, null=True),
        ),
    ]
