# Generated by Django 4.2.7 on 2023-11-21 14:14

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ("chatbots", "0003_content_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="embedding",
            field=pgvector.django.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
