# Generated by Django 4.2.7 on 2023-11-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbots", "0004_alter_chatbot_chatbot_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbot",
            name="dislike_count",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatbot",
            name="like_count",
            field=models.BigIntegerField(default=0),
        ),
    ]
