# Generated by Django 4.2.7 on 2023-11-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbots", "0005_chatbot_dislike_count_chatbot_like_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbot",
            name="is_disabled",
            field=models.BooleanField(default=False),
        ),
    ]
